### ISSUE TITLE
Increase size of Telegram icon in footer

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#116]
The icon of the Telegram channel in the footer has to be increased to be more noticeable.

**Comment by blackst0ne** [comment]
![image](https://user-images.githubusercontent.com/1610813/40519385-fd19e1da-600a-11e8-89df-d56cd733df45.png)

Increased a bit. 
@jamm1985 what do you think?

**Comment by blackst0ne** [comment]
ping @jamm1985

**Comment by jamm1985** [comment]
Please do the telegram icon twice as large.
