### ISSUE TITLE
Yandex Map tiles are broken

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#119]
![image](https://user-images.githubusercontent.com/1610813/42480834-21391cfe-842b-11e8-8e4f-49a416c34061.png)

There are some weird errors related to Yandex Maps tile servers. 
Occurs when switching tile servers on maps. 

Maybe yandex maps library should be updated? :thinking:

**Comment by blackst0ne** [comment]
Turned off the vue debug Google Chrome extension and everything becomes green. :thinking:

**Comment by blackst0ne** [comment]
There is a problem in Firefox: 

![image](https://user-images.githubusercontent.com/1610813/42481207-e7411b08-842c-11e8-831a-94b69834dd13.png)

**Comment by blackst0ne** [comment]
All the tile providers have been disabled for 2.0 release. 

There is only OpenStreetMap available. 

So removing the milestone from this issue.

**Comment by jamm1985** [comment]
Для релиза 2.0 мы выключили возможность выбора подложки яндекса. Необходимо сделать **опциональную** возможность выбора слоя яндекс-карт. То есть, по умолчанию всегда грузится подложка OSM, если кому то надо, то можно выбрать подложку яндекса.


<img width="1098" alt="2018-12-30 11 39 32" src="https://user-images.githubusercontent.com/3518847/50543280-be735c80-0c27-11e9-9c51-70013a484d13.png">

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.2 EQALERT.RU (фронт-энд)](https://trello.com/c/LRiuTR8m/7-%D1%8D%D1%82%D0%B0%D0%BF-22-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.2 EQALERT.RU (фронт-энд)](https://trello.com/c/LRiuTR8m/7-%D1%8D%D1%82%D0%B0%D0%BF-22-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)
