### ISSUE TITLE
Add HTML5 notifications

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#145]
Consider to add HTML5 notifications. 

/cc @jamm1985

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EQALERT 3.0 (отклики API, статика и обновление версий библиотек)](https://trello.com/c/YQqX69yr/290-eqalert-30-%D0%BE%D1%82%D0%BA%D0%BB%D0%B8%D0%BA%D0%B8-api-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D0%BA%D0%B0-%D0%B8-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA)

**Comment by blackst0ne** [comment]
@jamm1985 

No access. :)
