### ISSUE TITLE
Update static page content

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#156]
Please update the "Методика расчёта интенсивности по шкале MSK64" section according to attached document.

[fab8dcfaa30f76b4.docx](https://github.com/geophystech/eqalert.ru/files/2108725/fab8dcfaa30f76b4.docx)
(updated at 2018-06-17)

**Comment by blackst0ne** [comment]
I don't get how it should be. 

Should the title be changed from `Методика расчёта интенсивности по шкале MSK64` to `Методика расчёта интенсивности в ближайших населённых пунктах`?

**Comment by blackst0ne** [comment]
@jamm1985

**Comment by jamm1985** [comment]
> Should the title be changed from Методика расчёта интенсивности по шкале MSK64 to Методика расчёта интенсивности в ближайших населённых пунктах?

yes

**Comment by blackst0ne** [comment]
Deployed changes to staging. 
It's not merged into `master` yet. 

Please review.

https://eqalert-frontend-test.geophystech.ru/#/about
