### ISSUE TITLE
Plate boundaries

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#17]
@jamm1985 

At the current version of eqalert the mainpage shows the plate boundaries.  
They are saved in the `map.coffee` file. 

The questions are:

1. Should we show the boundaries on the mainpage map only as it is right now? 
2. Are we going to show them on other clients too (e.g. mobile apps)? 

The data is constant and doesn't get updates at all. 
At least there were none since we added them to eqalert.ru

**Comment by jamm1985** [comment]
> Should we show the boundaries on the mainpage map only as it is right now?

1. It's necessary to do accessible the plate boundaries as map's layer. 
2. The map on mainpage will not draws the P. Bird plate boundaries by default.
3. It will be good if we will do some UI enhancment that promt to use map's layers which not draw by default.

> Are we going to show them on other clients too (e.g. mobile apps)?

For mobile clients this is not necessary.
