### ISSUE TITLE
Update title on pages

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#175]
New schema should be `id | Землетрясение Mx.x | 100 км до г. Оха, о. Сахалин | EQA!ert`

**Comment by blackst0ne** [comment]
@jamm1985 we now have a tab name in titles like: 

```
Ближайшие населенные пункты | sjrhDGS2d | EQA!ert.ru
```

or 

```
Общая информация | sjrhDGS2d | EQA!ert.ru
```

Are we going to add them to the new schema? 

If yes, where should it be placed?

**Comment by blackst0ne** [comment]
Updated titles in #176 

![image](https://user-images.githubusercontent.com/1610813/42543956-1a24c8b2-84fa-11e8-81ed-c96bf6bc98e0.png)

There's no info about a nearest settlement yet. 

I created [an issue](https://github.com/geophystech/seismo-api/issues/58) in the API repo to check if the response is correct.   
If that's a bug, this issue is going to be blocked until the bug is fixed.   
If that's not, I'll add another explicit http-request.

**Comment by blackst0ne** [comment]
Updated: 

![image](https://user-images.githubusercontent.com/1610813/42739453-54ef04ac-88e3-11e8-92bb-47bb111638af.png)


@jamm1985 waiting for your reply on https://github.com/geophystech/eqalert.ru/issues/175#issuecomment-404001229

**Comment by jamm1985** [comment]
@blackst0ne : 

A pattern of title is: 
```
Землетрясение МХ.Х | ХХХ.ХХ км до town/city/village, REGION!! | event_id - EQA!lert
```

Please put tab name before `event_id - EQA!lert` like this:
```
Землетрясение МХ.Х | ХХХ.ХХ км до town/city/village, REGION!! | Tab Name | event_id - EQA!lert
```

**Comment by jamm1985** [comment]
@blackst0ne OK. The latest example is good!
