### ISSUE TITLE
Open map in fullscreen mode from About page

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#231]
The `About` page has the link: 

![image](https://user-images.githubusercontent.com/1610813/43493264-c5d03ef6-9578-11e8-8341-5629947a6f8e.png)

~~That link should lead to the mainpage and automatically open the map in fullscreen mode.~~

**Карта должна открываться в окне, как нас странице все землетрясения, и на ней должны отображаться только сейсмостанции.**

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Этап 2.5.0 EQALERT.RU (фронт-энд)](https://trello.com/c/o9Kah0Ud/68-%D1%8D%D1%82%D0%B0%D0%BF-250-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)
