### ISSUE TITLE
Баг с повтором событий в списке

### ISSUE THREAD

**Issue by bogdanevg** [geophystech/eqalert.ru#251]
<img width="884" alt="2018-08-06 21 29 06" src="https://user-images.githubusercontent.com/23372336/43711839-d0d8586a-99bf-11e8-88f2-a3983f6eea9e.png">

Воспроизводится случайно при переходе с главной страницы к списку, при авторизации, при обновлении страницы.
Воспроизводится в сафари, хроме, файерфоксе.

**Comment by jamm1985** [comment]
It will be fine if @blackst0ne will fixes it tomorrow!

**Comment by blackst0ne** [comment]
### Steps to reproduce:

1. Visit the mainpage.
2. Click on `Войти`.
3. Fill in all forms and login.
4. Afrer redirection to the mainpage, click on the `Все события` link.
5. See 4 XHR requests and duplicated events.

**Comment by blackst0ne** [comment]
Damn, still reproducible.
Reopening.

**Comment by blackst0ne** [comment]
Fixed by #256
