### ISSUE TITLE
Неправильный datetime_min для событий на главной карте

### ISSUE THREAD

**Issue by bogdanevg** [geophystech/eqalert.ru#264]
![2018-08-10 11 38 09](https://user-images.githubusercontent.com/23372336/43932909-6e16b9da-9c92-11e8-859c-c1ce9b5eab30.png)
Думаю надо изменить либо `datetime_min` для отображаемых событий, либо изменить легенду.

**Comment by jamm1985** [comment]
@blackst0ne if you have the time, please, look the issue and describe why it happened.

**Comment by jamm1985** [comment]
I suppose the setting is 6 month before. I think it's api case. @DoctorLines how many days before returns in case of unauthorized user?

**Comment by DoctorLines** [comment]
@jamm1985 In API request https://api-test.geophystech.ru/api/v1/reports with empty `datetime_min` field will defined as max available value by auth constraints. If no constraints, then no limits for `datetime_min`.

**Comment by jamm1985** [comment]
ОК. let's leave it until we will done export from usgs by 6 month. If that be hard to view on the map we will reduce to 3 month, if not - we will change the map legend.

/cc @blackst0ne, @DoctorLines

**Comment by jamm1985** [comment]
@blackst0ne I would like you to reduce 6 -> 3 month on a map in the main page. Please do 2.0.1 release for deploy.
