### ISSUE TITLE
Кнопка "Снять ограничение данных"

### ISSUE THREAD

**Issue by bogdanevg** [geophystech/eqalert.ru#265]
После авторизации кнопка не пропадает.

**Comment by blackst0ne** [comment]
This change in `src/components/CountersHeader.vue` should do the trick: 

```diff
@@ -1,6 +1,6 @@
<template>
  <b-row class="infobar" align-v="center" no-gutters>
-   <b-col cols="2" md="4" class="text-center text-md-left">
+   <b-col cols="2" md="4" class="text-center text-md-left" v-if="!$store.getters.user.authenticated">
      <router-link to="/sign-in">
        <i class="fa fa-lg fa-lock align-middle" aria-hidden="true" />
        <span v-if="!$root.onMobile">Снять ограничения данных</span>
```

But it should be tested if the layout is still OK when the item gets hidden.

**Comment by jamm1985** [comment]
@armd-pro прошу исправить ошибки: 

**Пропал зеленый фон у попапа после входа/выхода**

<img width="1235" alt="2018-12-04 21 32 09" src="https://user-images.githubusercontent.com/3518847/49436207-a79a3f80-f80c-11e8-9d57-27e33f756f03.png">

<img width="1331" alt="2018-12-04 21 32 36" src="https://user-images.githubusercontent.com/3518847/49436212-ab2dc680-f80c-11e8-8d09-d482bc927cd7.png">


**Информация о загруженных событиях стала не по центру, прошу сделать по центру**:

<img width="1241" alt="2018-12-04 21 31 59" src="https://user-images.githubusercontent.com/3518847/49436248-c698d180-f80c-11e8-95a5-495e754547e8.png">

**Comment by jamm1985** [comment]
Фон у кнопки исправлен.
