### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#266]
Tasks:

- Set the new URL for production-ready API services: rest-api.eqalert.ru, oauth-web.eqalert.ru.
- Fix bug with a `has_final` = `YES`
- increase events limit on main page `100` -> `500`
- do v2.0.0 release archive on https://github.com/geophystech/eqalert.ru/releases
- delete all unused branches.
- ensure packages.json has correct version of release

**Comment by blackst0ne** [comment]
Done by https://github.com/geophystech/eqalert.ru/pull/267

**Comment by blackst0ne** [comment]
Branches deleted

**Comment by blackst0ne** [comment]
Tagged. https://github.com/geophystech/eqalert.ru/releases/tag/v2.0.0

**Comment by jamm1985** [comment]
done: https://eqalert.ru/
