### ISSUE TITLE
Мерцание строки ближайших населенных пунктов

### ISSUE THREAD

**Issue by bogdanevg** [geophystech/eqalert.ru#269]
При наведении указателя мыши на значок подсказки ощущаемости строка населенного пункта и окно подсказки мерцает так, что прочитать содержимое не реально. Такое замечено у н.п. с ощущаемостью 5 и 6 баллов.
На скриншоте как раз запечатлено мерцающее окно. Chrome, в Safari мерцает чуть меньше.
![2018-10-26 16 22 01](https://user-images.githubusercontent.com/23372336/47546151-9a4f8280-d93b-11e8-931f-d73cfa621618.png)

**Comment by jamm1985** [comment]
@armd-pro спасибо!
