### ISSUE TITLE
Интерактивные переключатели на главной странице

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#270]
На главной странице необходимо реализовать интерактивные переключатели в виде кнопок на карте:

- события за последние сутки
- события за неделю
- события за последние три месяца

По сути нужно сделать интерактивным вот этот блок: 

<img width="1188" alt="2018-11-04 23 31 40" src="https://user-images.githubusercontent.com/3518847/47964190-02b00980-e08a-11e8-9f35-9f2ffe30d343.png">

Улучшения приветствуются.

**Comment by jamm1985** [comment]
@armd-pro прошу поправить: при нажатии на кнопку home мастаб не сохраняется.

**Comment by armd-pro** [comment]
> @armd-pro прошу поправить: при нажатии на кнопку home мастаб не сохраняется.

Поправил.

**Comment by jamm1985** [comment]
@armd-pro всё хорошо, спасибо!
