### ISSUE TITLE
Добавить кнопки выгрузки данных в XLSX

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#273]
Необходимо добавить возможность выгрузки данных в XLSX и CSV для авторизованных пользователей данных на следующих страницах:

- https://eqalert.ru/#/events (то что сейчас загружено на странице с учётом фильтров)
- на страницах событий, например, https://eqalert.ru/#/events/QgpAn7OW ,формируем вкладки XLSX аналогично тем, что на странице. Для CSV делаем архив вкладка=файл.

Наименование полей аналогично тем, что приходят от API.

**Comment by jamm1985** [comment]
@armd-pro : 

1. Формирование данных в XLSX/CSV должна выполнятся браузером. В зависимости от того, какой плагин вы будет использовать, нужно будет дать название кнопке:
<img width="1282" alt="2018-12-10 10 46 00" src="https://user-images.githubusercontent.com/3518847/49704592-03c7ee00-fc69-11e8-9abe-65a5db18be03.png">

2. Скачивание данных должно быть доступна на двух типах страниц:
- https://eqalert.ru/#/events (все события)
- https://eqalert.ru/#/events/`<event_ID>` (страница конкретного землетярсения)

3. Как формировать выгрузку на странице https://eqalert.ru/#/events (все события)
Это должен быть файл (1 лист в формате XLS, 1 файл в CSV) в котором в первой строке стоят названия всех полей из https://rest-api.eqalert.ru/apidoc/#api-Reports-GetList а далее идут строки с землетрясениями **которые в настоящий момент загружены на экране**. В выгрузке должны быть **все поля** которые прилетают в JSON!
<img width="1293" alt="2018-12-10 10 52 34" src="https://user-images.githubusercontent.com/3518847/49704669-00813200-fc6a-11e8-8927-a8bc4e950347.png">
**То есть** Если мы нажмем кнопку показать больше, и снова нажмем скачать, то в выгрузке должны отобразится все события которые сейчас загружены.

4. Как формировать выгрузку https://eqalert.ru/#/events/`<event_ID>` (страница конкретного землетярсения).
- в случае XLSX это 1 файл с несколькими листами (общая информация, ближайшие населённые пункты, здания и сооружения, магистральные объекты).
- в случае CSV это должен быть ZIP архив с несколькими файлами(общая информация, ближайшие населённые пункты, здания и сооружения, магистральные объекты).

**общая информация** - все поля из метода https://rest-api.eqalert.ru/apidoc/#api-Reports-GetReport для этого сбытия.

**ближайшие населённые пункты** - все поля из метода https://rest-api.eqalert.ru/apidoc/#api-MSK64-GetCitiesAnalysis для данного события. Загружаем **первые 300 городов**

**здания и сооружения** - все поля из метода получения состояния зданий и сооружений (только что делали в #272 ) для данного события.

**Магистральные объекты** - все поля из метода получения состояния магистральных объектов (только что делали в #272 ) для данного события.

**Comment by DoctorLines** [comment]
@jamm1985 А как ожидается в таблице увидеть поля, которые содержат вложенные данные?
во всех методах есть таковые (`locValues`, `nearestCity`)
https://rest-api.eqalert.ru/apidoc/#api-Reports-GetReport

А метод https://rest-api.eqalert.ru/apidoc/#api-Reports-GetList вообще может с пагинацией быть. Какое кол-во записей ожидается там выгружать? 
Одна строка в excel - один объект?

**Comment by jamm1985** [comment]
@DoctorLines 

Вложенные объекты записываем в одну строку. Так как для каждого объекта одинаковый набор полей во вложенных объектах, то можно делать фиксированный набор полей.

> А метод https://rest-api.eqalert.ru/apidoc/#api-Reports-GetList вообще может с пагинацией быть. 

Там есть параметр limit. Если пришел запрос с фильтрами или без, то ставим limit по умолчанию 5000. Если у нас будет случай выхода за limit 5000, то последняя строка должна содержать сообщение, что вывод обрезан по причине превышения лимита.

**Comment by jamm1985** [comment]
## UPDATE 1:

Добавлен новый параметр `export_to` = `xlsx` в следующие методы:

- https://rest-api.eqalert.ru/apidoc/#api-Reports-GetList
- https://rest-api.eqalert.ru/apidoc/#api-Reports-GetReport

Этот параметр позволяет запрашивать данные в формате xlsx, в ответ приходит ссылка на файл. В документации есть примеры корректного ответа от API:

<img width="1060" alt="2018-12-19 11 51 00" src="https://user-images.githubusercontent.com/3518847/50191970-71200100-0384-11e9-856a-26164bda5979.png">

## UPDATE 2:

Для авторизованных пользователей нужно делать проверку на наличие прав выгрузки в XLSX. Если права есть, то кнопка выгрузки появляется в двух местах, если прав нет, то кнопка не отрисовывается.

Проверять права нужно вот этим методом: https://rest-api.eqalert.ru/apidoc/#api-Authenticate_OAuth-TokenScopes

Пример ответа, когда права на выгрузки в xlsx **есть**:

<img width="676" alt="2018-12-19 11 55 38" src="https://user-images.githubusercontent.com/3518847/50192140-2b176d00-0385-11e9-8505-e8998e090c6a.png">


/to @armd-pro 

/cc @DoctorLines @bogdanevg

**Comment by jamm1985** [comment]
Протестировано.
