### ISSUE TITLE
Разрешить варнинги при сборке

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#310]
<img width="1424" alt="2018-12-30 23 00 22" src="https://user-images.githubusercontent.com/3518847/50547077-cf9f8600-0c86-11e9-96e5-0fe2fa5be6ee.png">

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.2 EQALERT.RU (фронт-энд)](https://trello.com/c/LRiuTR8m/7-%D1%8D%D1%82%D0%B0%D0%BF-22-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)

**Comment by armd-pro** [comment]
Эти зависимости указаны в самих зависимых пакетах проекта, которые надо развернуть в ручную.
Но  о них можно потом забыть и они так и останутся мёртвым грузом в проекте.
Да и нет необходимости в них.
Так что можно игнорировать эти предупреждения.
