### ISSUE TITLE
Добавить кнопку "Показать учебные"

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#315]
На странице "Все землетрясения", для пользователей у которых есть следующие права (смотреть [вот этим](https://rest-api.eqalert.ru/apidoc/#api-Authenticate_OAuth-TokenScopes) методом):

```
- reports:view_training
- reports
```

добавить кнопку - показать учебные:

<img width="1340" alt="2019-01-02 18 30 10" src="https://user-images.githubusercontent.com/3518847/50583381-e7f8e600-0ebc-11e9-9e03-c34c5884108e.png">

Если кнопка включена, то запрос событий ( [вот этот метод](https://rest-api.eqalert.ru/apidoc/#api-Reports-GetList) ) выполняется с параметром `has_training` = `true`

Если кнопка включена, то на странице `все землетрясения` вставляет баннер аналогично #311 

Кнопку надо сделать так, что было понятно когда она включена, а когда выключена. Например, можно сделать её серым когда кнопка не активна как кнопка ("Показать на карте"), а когда включена, то оранжевым или красным. Можно сделать переключателем в стиле ios.

Название кнопки: "Показать учебные"

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.2 EQALERT.RU (фронт-энд)](https://trello.com/c/LRiuTR8m/7-%D1%8D%D1%82%D0%B0%D0%BF-22-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)

**Comment by DoctorLines** [comment]
@jamm1985 
Показать учебные - это же фильтр поиска, по сути.
Почему его не в списке фильтров решил сделать (в виде галочки), а в качестве отдельной кнопки где-то в интерфейсе?

**Comment by jamm1985** [comment]
@DoctorLines вообще, действительно, можно в виде кнопки. Я хотел выделить эту функцию более ярко. Просто эта функция будет доступна сильно ограниченному крургу лиц. Возможно стоит кнопку добавить в панель фильтрации вместо верхней панели.
