### ISSUE TITLE
Исправить некорректные запросы на API

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#326]
При задании фильтра магнитуды в панели фильтрации на API отправляются некорректный запрос, а именно, не отправляется параметр `mag_min` в запросе [get list](https://rest-api.eqalert.ru/apidoc/#api-Reports-GetList)

![image](https://user-images.githubusercontent.com/3518847/52021056-ac971900-2547-11e9-85b6-7ecacc1c2f70.png)

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.3 EQALERT.RU (фронт-энд)](https://trello.com/c/2XGUeA85/49-%D1%8D%D1%82%D0%B0%D0%BF-23-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)

**Comment by armd-pro** [comment]
На скриншоте mag_min выставлен в "0". Разве это не тоже самое что "пусто"?
mag_max выставлен, значит должно вернут всё, до mag_max.

**Comment by jamm1985** [comment]
`0` - это не то же самое что и пусто. В принципе, почти всегда `0` - это есть именно `0`. Например, диапазон значений для магнитуды `[-10..10]` и ноль там, конечно, есть.

Это касается всех параметров (глубина, RMS и тд). Прошу их все проверить.

**Comment by jamm1985** [comment]
<img width="1238" alt="2019-02-17 17 49 06" src="https://user-images.githubusercontent.com/3518847/52909428-5e6e6d80-32dc-11e9-8788-40d77d1ca584.png">

Вот в этом примере должны быть выданы только магнитуды от 0 до 0.2 (включительно). А в выдаче есть отрицательные значения. Это потому что `mag_min = 0` не передаётся, хотя пользователь задал это значение.

**Comment by armd-pro** [comment]
Да я-то думал, что минимальное значение ноль, а не отрицательное.
Теперь ясно.
