### ISSUE TITLE
Нелогичный автоматический сброс авторизации

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#329]
## Проблема

При работе с сайтом происходит сброс авторизации. То есть приходится вводить пароль заново. Это происходит в любом случае, даже если поставить галочку "Запомнить меня". 

## Задачи

1. Необходимо критически изучить текущий механизм аторизации на предмет возможностей несанкционированного доступа. 
2. Устранить текущие проблемы безопасности, если они есть.
3. Сделать корректным обновление токена при установке галочки "Запомнить меня". Сброс авторизации при установлении этой галочки должен происходить через 14 дней. То есть, после истечении этого срока пользователь должен ввести пароль повторно.
4. Если галочка "Запомнить меня" не установлена, то автоматический сброс должен быть выполнен через 24 часа.

Документацию по методам обновления токенов через веб-клиент прилагаю. Текущие URL можно посмотреть прямо в коде.

[README.md.zip](https://github.com/geophystech/eqalert.ru/files/2862772/README.md.zip)

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.3 EQALERT.RU (фронт-энд)](https://trello.com/c/2XGUeA85/49-%D1%8D%D1%82%D0%B0%D0%BF-23-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)

**Comment by armd-pro** [comment]
Через ~24 часа, после получения токена авторизации, сам refresh_token уже не валиден.
![_002](https://user-images.githubusercontent.com/4474900/53006038-6a3e6900-346f-11e9-8388-61d300314266.png)

**Comment by DoctorLines** [comment]
> Через ~24 часа, после получения токена авторизации, сам refresh_token, который нужен для обновления токена авторизации, уже не валиден.

@armd-pro Очень похоже на то, что новый токен по данному `refresh_token` уже запрашивался. Да, он одноразовый.

Сам же `refresh_token` сейчас действителен 7 дней.

**Comment by armd-pro** [comment]
Запрашивался 1 раз, при авторизации.
Сам auth token сколько живёт?

>>> Сам же `refresh_token` сейчас действителен 7 дней.
Удвойте пожалуйста.

**Comment by DoctorLines** [comment]
У самого токена время жизни 24 часа. Эта информации выдается в json вместе с самим токеном.
Уже удвоил.

По ошибке очень похоже, что запрашивается повторно.

**Comment by armd-pro** [comment]
Благодарю.
Каждый раз, когда приходит refresh_token, локальное значение в хранилище перезаписывается.
Т.е. используется всегда новый refresh_token.

**Comment by DoctorLines** [comment]
Посмотрел логи.
Действительно есть два запроса на `refreshToken` сделанные почти в одно мгновение.

И видно, один вернул ответ 200, а следующий 401

![screenshot 2019-02-19 at 22 53 37](https://user-images.githubusercontent.com/10769555/53016339-219ba580-3499-11e9-90ea-4cb97f758ee2.png)

и по размеру body видно, что первый раз было много данных, т.к. токен в них лежал, а во второй раз просто текст с ошибкой. 
Время UTC

**Comment by armd-pro** [comment]
@DoctorLines Как Вы это выявили?
Что сделали, что сайт запросил refreshToken?

**Comment by DoctorLines** [comment]
@armd-pro Это не я. Просто глянул лог за сегодня, за последние 8 часов на запросы к oauth-web.eqalert.ru к /refreshToken

Было не сложно найти, т.к. таких запросов довольно мало.

**Comment by armd-pro** [comment]
@DoctorLines, можно уменьшить время жизни access токена до 30 минут, пока не закроем эту задачу.
Надо протестить, отловить причину данного поведения.
Не ждать же сутки каждый раз))

**Comment by DoctorLines** [comment]
У нас для подобных тестов есть тестовое API. 
Там можно легко уменьшить как будет удобно.
Могу сделать сейчас.

**Comment by armd-pro** [comment]
Ага, сделайте пожалуйста.
Какой там хост?

**Comment by armd-pro** [comment]
> время жизни access токена до 15 минут

Лучше 5 минут.

**Comment by DoctorLines** [comment]
api
https://api-test.geophystech.ru/
поставил 300 сек время жизни

oauth клиент (копия oauth-web.eqalert.ru):
https://oauth-client-test.geophystech.ru/

**Comment by armd-pro** [comment]
Благодарю, @DoctorLines!

**Comment by armd-pro** [comment]
@DoctorLines , консоль браузера всё это время была открыта.
![_002](https://user-images.githubusercontent.com/4474900/53091227-603e6800-354c-11e9-94f6-696b5403ce98.png)

**Comment by armd-pro** [comment]
И проблема при получении токена на тестовом.
Отваливается по таймауту.

![_004](https://user-images.githubusercontent.com/4474900/53092708-6fbfb000-3550-11e9-803e-3e3d790fbd16.png)

**Comment by jamm1985** [comment]
@armd-pro была внутренняя проблема на тестовом сервере. Поправили. Щас должно работать.

**Comment by armd-pro** [comment]
Разобрался. Логика перегрузки access токена следующая:
если запрос завершается с ошибкой 401 то запрос релоадится предварительно обновив токен.
А т.к. разные компоненты выполняют запрос с access токеном к апи в один промежуток времени (асинхронный javascript), то и вышеописанный механизм срабатывал для каждого случая одновременно.
Потребовалось функционал сброса токена обернуть в отдельную функцию, которая сама следит за тем, что она запущена в единственном экземпляре (singleton pattern), пока не завершится refresh token запрос.
Подсказку нашёл [тут](https://github.com/axios/axios/issues/266#issuecomment-335420598)
