### ISSUE TITLE
Лого appstore и google play на главной странице

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#330]
Необходимо подобрать ч/б логотипы appstore и google play и разместить их в хедере и подвале. Хедере можно сделать в уменьшенном варианте. В подвале в более крупном. Значек телеграма в подвале можно то же увеличить, если он будет смотрется мелким на фоне новых бейджов.

Ссылка на логотип app store: https://itunes.apple.com/ru/app/eqalert/id1448087679

Ссылка на логотип google play: 
https://play.google.com/store/apps/details?id=ru.geophystech.eqalert

[Графика APP_Store.zip](https://github.com/geophystech/eqalert.ru/files/2862822/APP_Store.zip)

[google-play-badge.png.zip](https://github.com/geophystech/eqalert.ru/files/2862828/google-play-badge.png.zip)

![screenshot_2019-02-14 eqa ert](https://user-images.githubusercontent.com/3518847/52765644-d2a8d700-3078-11e9-82ab-d4a1d7a244e8.png)

**Comment by armd-pro** [comment]
Может, лучше в одном стиле?

![mobile_store svg](https://user-images.githubusercontent.com/4474900/53282271-6dd43780-3770-11e9-9a8d-2e9e7bfd681f.png)

**Comment by armd-pro** [comment]
Надо с яблоком найти только))

**Comment by armd-pro** [comment]
Нашёл.

![seekpng com_google-play-logo-png_349265](https://user-images.githubusercontent.com/4474900/53282348-62354080-3771-11e9-9edc-b16df2ab6136.png)

**Comment by armd-pro** [comment]
Не первый вариант мне больше нравится.
И всё же, эти иконки какие-то громадные.

**Comment by jamm1985** [comment]
@armd-pro главное что бы мы имели право использовать кастомные иконки. Иногда на изображения налагаются лицензии по которым мы не можем их использовать. Поэтому я прикрепил официальные бейджы.

Предлагаю так: 
- в хедер поместить просто текстом Apple iOS / Android / telegram
- в подвал поместить официальные бейджы

**Comment by armd-pro** [comment]
Я взял бесплатные.
