### ISSUE TITLE
Добавить предложение на страницу "О проекте"

### ISSUE THREAD

**Issue by jamm1985** [geophystech/eqalert.ru#336]
На странице о проекте необходимо добавить следующее предложение:

Информация об исторической сейсмичности на территории Сахалина в период с 1905 по 2005 год добавлена по данным Регионального каталога землетрясений [Поплавская и др., 2006].

При наведении на [Поплавская и др., 2006] отображать вот это:

`Региональный каталог землетрясений о. Сахалин, 1905-2005 / Л.Н. Поплавская и др. – Южно-Сахалинск, ИМГиГ ДВО РАН, 2006. 104 с.`

Отображать надо так же, как отображается PGA / PGV / PSA ниже по тексту.

Вставить надо вот сюда: 

<img width="1263" alt="2019-02-15 0 26 02" src="https://user-images.githubusercontent.com/3518847/52789920-4ff43c00-30b9-11e9-949b-7d9c33ab7865.png">

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.3 EQALERT.RU (фронт-энд)](https://trello.com/c/2XGUeA85/49-%D1%8D%D1%82%D0%B0%D0%BF-23-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)

**Comment by Syler1984** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Интегрировать трехкомпонентную и одномерную модель распознавания P/S волн в SEISAN-3](https://trello.com/c/i1C9apje/199-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%82%D1%80%D0%B5%D1%85%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BD%D1%83%D1%8E-%D0%B8-%D0%BE%D0%B4%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D1%83%D1%8E-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C-%D1%80%D0%B0%D1%81%D0%BF%D0%BE%D0%B7%D0%BD%D0%B0%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-p-s-%D0%B2%D0%BE%D0%BB%D0%BD-%D0%B2-seisan-3)
