### ISSUE TITLE
History mode

### ISSUE THREAD

**Issue by bogdanevg** [geophystech/eqalert.ru#389]
В целях SEO оптимизации необходимо доработать приложение, исключив знак `#` из url'a:

```
https://eqalert.ru/#/ -> https://eqalert.ru
https://eqalert.ru/#/events -> https://eqalert.ru/events 
https://eqalert.ru/#/analytics -> https://eqalert.ru/analytics

И т.д.
```

В документации vue.js описан [способ](https://router.vuejs.org/guide/essentials/history-mode.html) с использованием HTML5 history mode.

Необходимо убедиться, что все маршруты отрабатывают корректно.

Также необходимо убедиться, что переходы по старым ссылкам со знаком `#` отрабатывают корректно. При необходимости исключать `#` из url'а динамически.

**Comment by bogdanevg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Динамический рендеринг для eqalert.ru (SEO оптимизация)](https://trello.com/c/6C7PMAMQ/198-%D0%B4%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B8%D0%BD%D0%B3-%D0%B4%D0%BB%D1%8F-eqalertru-seo-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F)

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EQALERT 3.0 (отклики API, статика и обновление версий библиотек)](https://trello.com/c/YQqX69yr/290-eqalert-30-%D0%BE%D1%82%D0%BA%D0%BB%D0%B8%D0%BA%D0%B8-api-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D0%BA%D0%B0-%D0%B8-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA)

**Comment by NikitaMakovey** [comment]
https://github.com/NikitaMakovey/eqalert.ru/pull/1
