### ISSUE TITLE
Group events on mainpage map

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#40]
Now it's quite hard to distinguish events on the mainpage map if there are many ones in the same region. 

Example: 

![image](https://user-images.githubusercontent.com/1610813/32756151-b8d8862c-c92c-11e7-847e-71a1132f2830.png)

Events should be grouped with indication of how many events are inside each group.

**Comment by jamm1985** [comment]
Группировка в данном случае не нужна.
