### ISSUE TITLE
Доработки по откликам 

### ISSUE THREAD

**Issue by bogdanevg** [geophystech/eqalert.ru#423]
Список исправлений:

Принципиальные замечания:

1. От всех значений интенсивности нужно отнять 0.2, тогда интенсивность приобретет смысл ШСИ-2017.

2. Зеленые квадратики можно оставить, но при клике должна появляться информация не только о сейсмической интенсивности, но и количестве респондентов и названии населенного пункта.

3. Зеленые квадратики должны быть на двух вариантах карт: на вкладке «Общая информация» (https://eqalert-frontend-test.geophystech.ru/events/dBGGg5By?backUrlQuery=%7B%7D) и на вкладке «Ближайшие населенные пункты» (https://eqalert-frontend-test.geophystech.ru/events/dBGGg5By/settlements?backUrlQuery=%7B%7D).

4. Во вкладке «Ближайшие населенные пункты» (https://eqalert-frontend-test.geophystech.ru/events/dBGGg5By/settlements?backUrlQuery=%7B%7D) надо добавить информацию «Количество откликов».

5. В текущей версии eqalert показывается только 10 ближайших населенных пунктов во вкладке интернет браузера: https://eqalert-frontend-test.geophystech.ru/events/dBGGg5By/settlements?backUrlQuery=%7B%7D. Надо добавить опцию «показать еще» как например это сделано при поиске событий.

6. По умолчанию необходимо запускать Яндекс карту и линейку писать на русском, то есть вместо km писать км.

7. Баллы - баллов до сих пор с ошибкой. 
2 балла
3 балла
4 балла
5 баллов
6 баллов
7 баллов
8 баллов
9 баллов
10 баллов
11 баллов
12 баллов

8. У некоторых событий неверное количество откликов в пункте Отклики. Например: https://eqalert.ru/events/EA4k5gbD
Количество откликов события берется из параметра `felt_reports_count`

9. У события https://eqalert.ru/events/RAoJvKbY
не рисуются отклики на карте на вкладке Общая информация, хотя у события есть отклики.

10. Добавить в фильтры параметр "С откликами от населения" 

```
has_felt_reports = true
```

11. Исправить опечатку в слове "Отклики" на виджете выбора слоев карты события

![Снимок экрана 2022-12-19 в 16 14 36](https://user-images.githubusercontent.com/23372336/208352708-f2c981d6-7ef0-4e56-9c17-b37e2585b935.png)

**Comment by bogdanevg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EQALERT 3.1](https://trello.com/c/43qrGSt8/336-eqalert-31)

**Comment by NikitaMakovey** [comment]
Done
