### ISSUE TITLE
Fix layers control

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/eqalert.ru#64]
When a page with map is loaded, the layers control element does not have any base layers selected despite in fact a layer has been loaded. 

![image](https://user-images.githubusercontent.com/1610813/35546751-afa9d8e2-05c9-11e8-871e-1c7ba5e713b3.png)

It should be fixed.

**Comment by jamm1985** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ЭТАП 2.2 EQALERT.RU (фронт-энд)](https://trello.com/c/LRiuTR8m/7-%D1%8D%D1%82%D0%B0%D0%BF-22-eqalertru-%D1%84%D1%80%D0%BE%D0%BD%D1%82-%D1%8D%D0%BD%D0%B4)
